spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    database-name: driveDb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8085
  error:
    include-message: always
jira:
  env:
    url: ${JIRA_TEST_URL}
    user-name: ${JIRA_TEST_USERNAME}
    password: ${JIRA_TEST_PASSWORD}
drive:
  env:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    base-url: ${BASE_URL}
templates:
  env:
    folder: ${TEMPLATES_FOLDER}