spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${vcap.services.my_db.credentials.username}
    password: ${vcap.services.my_db.credentials.password}
    url: jdbc:postgresql://${vcap.services.my_db.credentials.hostname}:${vcap.services.my_db.credentials.port}/${vcap.services.my_db.credentials.dbname}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: ${vcap.services.cache_db.credentials.port}
    host: ${vcap.services.cache_db.credentials.hostname}
    password: ${vcap.services.cache_db.credentials.password}
  cache:
    type: redis
    cache-names: employees
server:
  error:
    include-message: always
drive:
  env:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    base-url: ${BASE_URL}
jira:
  env:
    url: ${JIRA_TEST_URL}
    user-name: ${JIRA_TEST_USERNAME}
    password: ${JIRA_TEST_PASSWORD}
templates:
  env:
    folder: ${TEMPLATES_FOLDER}