spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    database-name: board_db
    username: postgres
    password: example
    hostname: database
    port: 5432
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-message: always
  port: 8085
drive:
  env:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    base-url: ${BASE_URL}
jira:
  env:
    url: ${JIRA_TEST_URL}
    user-name: ${JIRA_TEST_USERNAME}
    password: ${JIRA_TEST_PASSWORD}
templates:
  env:
    folder: ${TEMPLATES_FOLDER}